### ISSUE TITLE
where is SUNRGBD data loading code？

### ISSUE THREAD

**Issue by YChao99** [anwesanpal/DEDUCE#3]
hello！I read your paper and project, but I did not find the data loading code for SUNRGBD dataset and VPC dataset. what should I do f I want to use these two datasets？

**Comment by anwesanpal** [comment]
Hello! The dataloader used in this code is the standard PyTorch Image dataloader. As long as the data is stored in a pattern similar to `/path_to_data/{dataset}/env_type/train/scene_type/*.jpg` structure , the loader should work.
